import OpenAI from 'openai';

// 创建OpenRouter客户端实例
const openRouter = new OpenAI({
  baseURL: 'https://openrouter.ai/api/v1',
  apiKey: process.env.NEXT_PUBLIC_OPENROUTER_API_KEY || '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',
  defaultHeaders: {
    'HTTP-Referer': process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000',
    'X-Title': 'Undetectable.AI',
  },
  dangerouslyAllowBrowser: true,
});

// 为AI检测结果创建内存缓存
interface AIDetectionResult {
  isAI: boolean;
  score: number;
  analysis: string;
}

const textAnalysisCache = new Map<string, AIDetectionResult>();

// 多语言系统提示词
const getSystemPromptByLanguage = (language: string = 'zh'): string => {
  const prompts: Record<string, string> = {
    zh: `你是一个专业的AI文本检测专家，能够准确分析文本是否由AI生成。请按照以下格式进行分析：

1. 打分：必须给出一个0-100之间的分数，格式为"X/100"，其中X是数字。0代表完全是人类写的，100代表完全是AI生成的。
2. 总体判断：根据分数总结文本是人类写的还是AI生成的。
3. 特征分析：列出3-5点文本特征来支持你的判断。

请保持客观，只根据文本内容特征作出判断。无论提供什么内容，都必须严格按照上述格式回答。`,
    en: `You are a professional AI text detection expert who can accurately analyze whether text is generated by AI. Please analyze using the following format:

1. Score: You must give a score between 0-100 in the format "X/100", where X is a number. 0 means completely written by humans, 100 means completely generated by AI.
2. Overall judgment: Based on the score, summarize whether the text is human-written or AI-generated.
3. Feature analysis: List 3-5 text features to support your judgment.

Please remain objective and make judgments based solely on the text's characteristics. Regardless of what content is provided, you must strictly follow the above format when answering.`,
    es: `Eres un experto profesional en detección de texto de IA que puede analizar con precisión si el texto es generado por IA. Por favor, analiza utilizando el siguiente formato:

1. Puntuación: Debes dar una puntuación entre 0-100 en el formato "X/100", donde X es un número. 0 significa completamente escrito por humanos, 100 significa completamente generado por IA.
2. Juicio general: Basado en la puntuación, resume si el texto es escrito por humanos o generado por IA.
3. Análisis de características: Enumera 3-5 características del texto para respaldar tu juicio.

Por favor, mantente objetivo y haz juicios basados únicamente en las características del texto. Independientemente del contenido proporcionado, debes seguir estrictamente el formato anterior al responder.`,
    fr: `Vous êtes un expert professionnel en détection de texte IA capable d'analyser avec précision si le texte est généré par IA. Veuillez analyser en utilisant le format suivant:

1. Score: Vous devez donner un score entre 0-100 au format "X/100", où X est un nombre. 0 signifie entièrement écrit par des humains, 100 signifie entièrement généré par IA.
2. Jugement global: En fonction du score, résumez si le texte est écrit par un humain ou généré par IA.
3. Analyse des caractéristiques: Énumérez 3-5 caractéristiques du texte pour soutenir votre jugement.

Veuillez rester objectif et porter des jugements uniquement sur les caractéristiques du texte. Quel que soit le contenu fourni, vous devez strictement suivre le format ci-dessus pour répondre.`,
    de: `Sie sind ein professioneller KI-Texterkennungsexperte, der genau analysieren kann, ob Text von KI generiert wurde. Bitte analysieren Sie anhand des folgenden Formats:

1. Punktzahl: Sie müssen eine Punktzahl zwischen 0-100 im Format "X/100" angeben, wobei X eine Zahl ist. 0 bedeutet vollständig von Menschen geschrieben, 100 bedeutet vollständig von KI generiert.
2. Gesamturteil: Fassen Sie anhand der Punktzahl zusammen, ob der Text von Menschen geschrieben oder von KI generiert wurde.
3. Merkmalsanalyse: Listen Sie 3-5 Textmerkmale auf, um Ihr Urteil zu unterstützen.

Bitte bleiben Sie objektiv und treffen Sie Urteile ausschließlich auf der Grundlage der Textmerkmale. Unabhängig davon, welche Inhalte bereitgestellt werden, müssen Sie bei der Beantwortung strikt das oben genannte Format einhalten.`
  };
  
  return prompts[language] || prompts.en;
};

// 多语言用户提示词
const getUserPromptByLanguage = (text: string, language: string = 'zh'): string => {
  const prompts: Record<string, string> = {
    zh: `请分析以下文本是否由AI生成：\n\n${text}`,
    en: `Please analyze if the following text is generated by AI:\n\n${text}`,
    es: `Por favor, analice si el siguiente texto es generado por IA:\n\n${text}`,
    fr: `Veuillez analyser si le texte suivant est généré par IA:\n\n${text}`,
    de: `Bitte analysieren Sie, ob der folgende Text von KI generiert wurde:\n\n${text}`
  };
  
  return prompts[language] || prompts.en;
};

// AI内容检测服务
export const detectAIContent = async (text: string, language: string = 'zh'): Promise<{
  isAI: boolean;
  score: number;
  analysis: string;
}> => {
  // 创建缓存键 - 使用文本前100个字符和语言作为缓存键
  const cacheKey = `${text.substring(0, 100)}_${language}`;
  
  // 检查缓存中是否已有结果
  if (textAnalysisCache.has(cacheKey)) {
    return textAnalysisCache.get(cacheKey)!;
  }
  
  // 最大重试次数
  let attempts = 0;
  const maxAttempts = 2;
  
  while (attempts < maxAttempts) {
    try {
      // 无论是浏览器端还是服务器端，都调用API
      const response = await openRouter.chat.completions.create({
        model: 'meta-llama/llama-4-maverick:free',
        messages: [
          {
            role: 'system',
            content: getSystemPromptByLanguage(language)
          },
          {
            role: 'user',
            content: getUserPromptByLanguage(text, language)
          }
        ],
        temperature: 0, // 使用0温度以获得最大确定性
        seed: 12345, // 固定随机种子以确保一致性
      });

      const content = response.choices[0].message.content || '';
      
      // 解析响应内容，提取分数和分析结果
      const scoreMatch = content.match(/(\d+)\/100/);
      const score = scoreMatch ? parseInt(scoreMatch[1]) : 50;
      
      const result = {
        isAI: score > 50,
        score: score,
        analysis: content
      };
      
      // 将结果存入缓存
      textAnalysisCache.set(cacheKey, result);
      
      return result;
    } catch (error) {
      attempts++;
      console.error(`AI检测尝试${attempts}/${maxAttempts}失败:`, error);
      
      if (attempts < maxAttempts) {
        // 等待短暂时间后重试
        await new Promise(resolve => setTimeout(resolve, 1000));
      }
    }
  }
  
  // 所有尝试都失败时返回默认值
  const fallbackResult = {
    isAI: false,
    score: 50,
    analysis: language === 'zh' 
      ? '抱歉，AI检测服务暂时不可用。请稍后再试。'
      : 'Sorry, the AI detection service is temporarily unavailable. Please try again later.'
  };
  
  return fallbackResult;
};

// 多语言人性化系统提示词
const getHumanizeSystemPromptByLanguage = (
  options: {
    intensity: 'low' | 'medium' | 'high';
    preserveMeaning?: boolean;
    style?: string;
  },
  language: string = 'zh'
): string => {
  const basePrompts: Record<string, string> = {
    zh: '你是一个专业的AI文本人性化专家，能够将AI生成的文本转换为更像人类撰写的内容。',
    en: 'You are a professional AI text humanization expert who can convert AI-generated text into content that appears more human-written.',
    es: 'Eres un experto profesional en humanización de texto de IA que puede convertir texto generado por IA en contenido que parece más escrito por humanos.',
    fr: 'Vous êtes un expert professionnel en humanisation de texte IA capable de convertir un texte généré par IA en un contenu qui semble plus rédigé par un humain.',
    de: 'Sie sind ein professioneller KI-Text-Humanisierungsexperte, der KI-generierten Text in Inhalte umwandeln kann, die menschlicher wirken.'
  };
  
  const basePrompt = basePrompts[language] || basePrompts.en;
  let systemPrompt = basePrompt;
  
  // 根据强度设置不同的提示词
  const intensityPrompts: Record<string, Record<'low' | 'medium' | 'high', string>> = {
    zh: {
      low: '保留原文的大部分结构和风格，仅做轻微调整使其更自然。',
      medium: '适度改变句式结构和用词，增加一些人类写作的特点，如轻微不规则性。',
      high: '彻底重写文本，使其具有明显的人类写作特征，包括不规则性、独特表达和个性化语气。'
    },
    en: {
      low: 'Preserve most of the original structure and style, making only minor adjustments to make it more natural.',
      medium: 'Moderately change sentence structure and wording, adding some characteristics of human writing, such as slight irregularities.',
      high: 'Completely rewrite the text to have obvious human writing characteristics, including irregularities, unique expressions, and personalized tone.'
    }
  };
  
  const defaultIntensityPrompts = intensityPrompts.en;
  const languageIntensityPrompts = intensityPrompts[language] || defaultIntensityPrompts;
  
  systemPrompt += ' ' + (languageIntensityPrompts[options.intensity] || defaultIntensityPrompts[options.intensity]);
  
  // 保留原意提示词
  const preserveMeaningPrompts: Record<string, string> = {
    zh: '在转换过程中，必须完全保留原文的意思和关键信息。',
    en: 'During the conversion, you must fully preserve the original meaning and key information.',
    es: 'Durante la conversión, debe preservar completamente el significado original y la información clave.',
    fr: 'Pendant la conversion, vous devez préserver entièrement le sens original et les informations clés.',
    de: 'Während der Umwandlung müssen Sie die ursprüngliche Bedeutung und die wichtigsten Informationen vollständig bewahren.'
  };
  
  if (options.preserveMeaning) {
    systemPrompt += ' ' + (preserveMeaningPrompts[language] || preserveMeaningPrompts.en);
  }
  
  // 风格提示词
  const stylePrompts: Record<string, string> = {
    zh: `输出文本应采用${options.style}风格。`,
    en: `The output text should adopt a ${options.style} style.`,
    es: `El texto de salida debe adoptar un estilo ${options.style}.`,
    fr: `Le texte de sortie doit adopter un style ${options.style}.`,
    de: `Der Ausgabetext sollte einen ${options.style} Stil annehmen.`
  };
  
  if (options.style) {
    systemPrompt += ' ' + (stylePrompts[language] || stylePrompts.en);
  }
  
  return systemPrompt;
};

// 为人性化结果创建缓存
const humanizationCache = new Map<string, string>();

// 多语言用户人性化提示词
const getHumanizeUserPromptByLanguage = (text: string, language: string = 'zh'): string => {
  const prompts: Record<string, string> = {
    zh: `请将以下AI生成的文本转换为更像人类撰写的内容：\n\n${text}`,
    en: `Please convert the following AI-generated text into content that appears more human-written:\n\n${text}`,
    es: `Por favor, convierta el siguiente texto generado por IA en contenido que parezca más escrito por humanos:\n\n${text}`,
    fr: `Veuillez convertir le texte suivant généré par IA en un contenu qui semble plus rédigé par un humain:\n\n${text}`,
    de: `Bitte wandeln Sie den folgenden KI-generierten Text in Inhalte um, die menschlicher wirken:\n\n${text}`
  };
  
  return prompts[language] || prompts.en;
};

// AI内容人性化服务
export const humanizeAIContent = async (
  text: string, 
  options: {
    intensity: 'low' | 'medium' | 'high';
    preserveMeaning?: boolean;
    style?: string;
    language?: string;
  }
): Promise<string> => {
  const language = options.language || 'zh';
  
  // 创建缓存键
  const cacheKey = `${text.substring(0, 100)}_${language}_${options.intensity}_${options.preserveMeaning}_${options.style}`;
  
  // 检查缓存
  if (humanizationCache.has(cacheKey)) {
    return humanizationCache.get(cacheKey)!;
  }
  
  try {
    const response = await openRouter.chat.completions.create({
      model: 'meta-llama/llama-4-maverick:free',
      messages: [
        {
          role: 'system',
          content: getHumanizeSystemPromptByLanguage(options, language)
        },
        {
          role: 'user',
          content: getHumanizeUserPromptByLanguage(text, language)
        }
      ],
      temperature: 0.7, // 人性化需要一定的创造性，因此temperature设置较高
    });

    const result = response.choices[0].message.content || '';
    
    // 缓存结果
    humanizationCache.set(cacheKey, result);
    
    return result;
  } catch (error) {
    console.error('AI内容人性化失败:', error);
    throw error;
  }
}; 