import OpenAI from 'openai';

// 创建OpenRouter客户端实例
const openRouter = new OpenAI({
  baseURL: 'https://openrouter.ai/api/v1',
  apiKey: process.env.NEXT_PUBLIC_OPENROUTER_API_KEY || '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',
  defaultHeaders: {
    'HTTP-Referer': process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000',
    'X-Title': 'Undetectable.AI',
  },
  dangerouslyAllowBrowser: true,
});

// 多语言系统提示词
const getSystemPromptByLanguage = (language: string = 'zh'): string => {
  const prompts: Record<string, string> = {
    zh: '你是一个专业的AI文本检测专家，能够分析文本是否由AI生成。请分析提供的文本，并给出详细的判断理由。评分范围从0到100，其中0表示完全是人类撰写，100表示完全由AI生成。',
    en: 'You are a professional AI text detection expert who can analyze whether text is generated by AI. Please analyze the provided text and give detailed reasoning for your judgment. The score range is from 0 to 100, where 0 means completely written by humans and 100 means completely generated by AI.',
    es: 'Eres un experto profesional en detección de texto de IA que puede analizar si el texto es generado por IA. Analiza el texto proporcionado y da un razonamiento detallado para tu juicio. El rango de puntuación es de 0 a 100, donde 0 significa completamente escrito por humanos y 100 significa completamente generado por IA.',
    fr: 'Vous êtes un expert professionnel en détection de texte IA capable d\'analyser si le texte est généré par IA. Veuillez analyser le texte fourni et donner un raisonnement détaillé pour votre jugement. La plage de score va de 0 à 100, où 0 signifie entièrement écrit par des humains et 100 signifie entièrement généré par IA.',
    de: 'Sie sind ein professioneller KI-Texterkennungsexperte, der analysieren kann, ob Text von KI generiert wurde. Bitte analysieren Sie den bereitgestellten Text und geben Sie eine detaillierte Begründung für Ihr Urteil. Der Bewertungsbereich reicht von 0 bis 100, wobei 0 bedeutet, dass der Text vollständig von Menschen geschrieben wurde, und 100 bedeutet, dass er vollständig von KI generiert wurde.'
  };
  
  return prompts[language] || prompts.en;
};

// 多语言用户提示词
const getUserPromptByLanguage = (text: string, language: string = 'zh'): string => {
  const prompts: Record<string, string> = {
    zh: `请分析以下文本是否由AI生成：\n\n${text}`,
    en: `Please analyze if the following text is generated by AI:\n\n${text}`,
    es: `Por favor, analice si el siguiente texto es generado por IA:\n\n${text}`,
    fr: `Veuillez analyser si le texte suivant est généré par IA:\n\n${text}`,
    de: `Bitte analysieren Sie, ob der folgende Text von KI generiert wurde:\n\n${text}`
  };
  
  return prompts[language] || prompts.en;
};

// AI内容检测服务
export const detectAIContent = async (text: string, language: string = 'zh'): Promise<{
  isAI: boolean;
  score: number;
  analysis: string;
}> => {
  try {
    // 在浏览器端直接使用模拟数据，避免API调用问题
    if (typeof window !== 'undefined') {
      // 使用模拟数据
      const mockScore = Math.floor(Math.random() * 100) + 1; // 随机分数1-100
      const mockAnalysis = language === 'zh' 
        ? `分析结果：该文本的AI生成可能性为${mockScore}/100。\n\n特征分析：\n- 文本结构${mockScore > 50 ? '较为规整' : '不够规整'}\n- 用词选择${mockScore > 50 ? '过于精确' : '较为自然'}\n- 表达方式${mockScore > 50 ? '缺乏个性' : '具有个人风格'}`
        : `Analysis: The AI generation probability of this text is ${mockScore}/100.\n\nFeature analysis:\n- Text structure is ${mockScore > 50 ? 'too regular' : 'irregular'}\n- Word choice is ${mockScore > 50 ? 'too precise' : 'natural'}\n- Expression style ${mockScore > 50 ? 'lacks personality' : 'has personal style'}`;
      
      return {
        isAI: mockScore > 50,
        score: mockScore,
        analysis: mockAnalysis
      };
    }
    
    // 服务器端尝试调用API
    const response = await openRouter.chat.completions.create({
      model: 'meta-llama/llama-4-maverick:free',
      messages: [
        {
          role: 'system',
          content: getSystemPromptByLanguage(language)
        },
        {
          role: 'user',
          content: getUserPromptByLanguage(text, language)
        }
      ],
    });

    const content = response.choices[0].message.content || '';
    
    // 解析响应内容，提取分数和分析结果
    const scoreMatch = content.match(/(\d+)\/100/);
    const score = scoreMatch ? parseInt(scoreMatch[1]) : 50;
    
    return {
      isAI: score > 50,
      score: score,
      analysis: content
    };
  } catch (error) {
    console.error('AI检测失败:', error);
    // 出错时返回默认值而不是抛出错误，确保UI不会崩溃
    return {
      isAI: false,
      score: 50,
      analysis: language === 'zh' 
        ? '抱歉，AI检测服务暂时不可用。请稍后再试。'
        : 'Sorry, the AI detection service is temporarily unavailable. Please try again later.'
    };
  }
};

// 多语言人性化系统提示词
const getHumanizeSystemPromptByLanguage = (
  options: {
    intensity: 'low' | 'medium' | 'high';
    preserveMeaning?: boolean;
    style?: string;
  },
  language: string = 'zh'
): string => {
  const basePrompts: Record<string, string> = {
    zh: '你是一个专业的AI文本人性化专家，能够将AI生成的文本转换为更像人类撰写的内容。',
    en: 'You are a professional AI text humanization expert who can convert AI-generated text into content that appears more human-written.',
    es: 'Eres un experto profesional en humanización de texto de IA que puede convertir texto generado por IA en contenido que parece más escrito por humanos.',
    fr: 'Vous êtes un expert professionnel en humanisation de texte IA capable de convertir un texte généré par IA en un contenu qui semble plus rédigé par un humain.',
    de: 'Sie sind ein professioneller KI-Text-Humanisierungsexperte, der KI-generierten Text in Inhalte umwandeln kann, die menschlicher wirken.'
  };
  
  const basePrompt = basePrompts[language] || basePrompts.en;
  let systemPrompt = basePrompt;
  
  // 根据强度设置不同的提示词
  const intensityPrompts: Record<string, Record<'low' | 'medium' | 'high', string>> = {
    zh: {
      low: '保留原文的大部分结构和风格，仅做轻微调整使其更自然。',
      medium: '适度改变句式结构和用词，增加一些人类写作的特点，如轻微不规则性。',
      high: '彻底重写文本，使其具有明显的人类写作特征，包括不规则性、独特表达和个性化语气。'
    },
    en: {
      low: 'Preserve most of the original structure and style, making only minor adjustments to make it more natural.',
      medium: 'Moderately change sentence structure and wording, adding some characteristics of human writing, such as slight irregularities.',
      high: 'Completely rewrite the text to have obvious human writing characteristics, including irregularities, unique expressions, and personalized tone.'
    }
  };
  
  const defaultIntensityPrompts = intensityPrompts.en;
  const languageIntensityPrompts = intensityPrompts[language] || defaultIntensityPrompts;
  
  systemPrompt += ' ' + (languageIntensityPrompts[options.intensity] || defaultIntensityPrompts[options.intensity]);
  
  // 保留原意提示词
  const preserveMeaningPrompts: Record<string, string> = {
    zh: '在转换过程中，必须完全保留原文的意思和关键信息。',
    en: 'During the conversion, you must fully preserve the original meaning and key information.',
    es: 'Durante la conversión, debe preservar completamente el significado original y la información clave.',
    fr: 'Pendant la conversion, vous devez préserver entièrement le sens original et les informations clés.',
    de: 'Während der Umwandlung müssen Sie die ursprüngliche Bedeutung und die wichtigsten Informationen vollständig bewahren.'
  };
  
  if (options.preserveMeaning) {
    systemPrompt += ' ' + (preserveMeaningPrompts[language] || preserveMeaningPrompts.en);
  }
  
  // 风格提示词
  const stylePrompts: Record<string, string> = {
    zh: `输出文本应采用${options.style}风格。`,
    en: `The output text should adopt a ${options.style} style.`,
    es: `El texto de salida debe adoptar un estilo ${options.style}.`,
    fr: `Le texte de sortie doit adopter un style ${options.style}.`,
    de: `Der Ausgabetext sollte einen ${options.style} Stil annehmen.`
  };
  
  if (options.style) {
    systemPrompt += ' ' + (stylePrompts[language] || stylePrompts.en);
  }
  
  return systemPrompt;
};

// 多语言用户人性化提示词
const getHumanizeUserPromptByLanguage = (text: string, language: string = 'zh'): string => {
  const prompts: Record<string, string> = {
    zh: `请将以下AI生成的文本转换为更像人类撰写的内容：\n\n${text}`,
    en: `Please convert the following AI-generated text into content that appears more human-written:\n\n${text}`,
    es: `Por favor, convierta el siguiente texto generado por IA en contenido que parezca más escrito por humanos:\n\n${text}`,
    fr: `Veuillez convertir le texte suivant généré par IA en un contenu qui semble plus rédigé par un humain:\n\n${text}`,
    de: `Bitte wandeln Sie den folgenden KI-generierten Text in Inhalte um, die menschlicher wirken:\n\n${text}`
  };
  
  return prompts[language] || prompts.en;
};

// AI内容人性化服务
export const humanizeAIContent = async (
  text: string, 
  options: {
    intensity: 'low' | 'medium' | 'high';
    preserveMeaning?: boolean;
    style?: string;
    language?: string;
  }
): Promise<string> => {
  try {
    const language = options.language || 'zh';
    
    const response = await openRouter.chat.completions.create({
      model: 'meta-llama/llama-4-maverick:free',
      messages: [
        {
          role: 'system',
          content: getHumanizeSystemPromptByLanguage(options, language)
        },
        {
          role: 'user',
          content: getHumanizeUserPromptByLanguage(text, language)
        }
      ],
    });

    return response.choices[0].message.content || '';
  } catch (error) {
    console.error('AI内容人性化失败:', error);
    throw error;
  }
}; 