import React, { useState } from 'react';
import Layout from '../components/layout/Layout';
import { detectAIContent } from '../lib/openRouter';

// 支持的语言选项
const languages = [
  { value: 'zh', label: '中文' },
  { value: 'en', label: 'English' },
  { value: 'es', label: 'Español' },
  { value: 'fr', label: 'Français' },
  { value: 'de', label: 'Deutsch' },
];

export default function AIDetector() {
  const [inputText, setInputText] = useState('');
  const [selectedLanguage, setSelectedLanguage] = useState('en');
  const [result, setResult] = useState<{
    score: number;
    humanPercent: number;
    aiPercent: number;
    analysis: string;
  } | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [error, setError] = useState('');

  // 处理AI内容检测
  const handleDetection = async () => {
    if (!inputText.trim()) return;
    
    setIsAnalyzing(true);
    setError('');
    
    try {
      const response = await detectAIContent(inputText, selectedLanguage);
      
      setResult({
        score: response.score,
        humanPercent: 100 - response.score,
        aiPercent: response.score,
        analysis: response.analysis
      });
    } catch (err) {
      console.error('检测错误:', err);
      setError('内容检测失败，请稍后再试。');
    } finally {
      setIsAnalyzing(false);
    }
  };

  // 语言标签文本映射
  const langTexts = {
    zh: {
      title: 'AI内容检测器',
      description: '检测您的内容是否由AI生成，获取详细的分析报告和建议。',
      inputLabel: '输入文本',
      placeholder: '粘贴需要检测的文本（至少100个字符）...',
      characters: '个字符',
      minChars: '(建议至少100个字符)',
      analyzeButton: '检测文本',
      analyzing: '分析中...',
      resultTitle: '检测结果',
      aiProbability: 'AI可能性',
      humanScore: '人类得分',
      aiScore: 'AI得分',
      highAi: '这段文本很可能是由AI生成的。',
      mediumAi: '这段文本可能包含AI生成的部分内容。',
      lowAi: '这段文本很可能是由人类撰写的。',
      detailAnalysis: '详细分析',
      retestButton: '重新检测',
      humanizeButton: '人性化文本',
      enterText: '输入文本并点击"检测文本"按钮以获取分析结果',
      howItWorks: 'AI检测器是如何工作的？',
      contentAnalysis: '内容分析',
      contentAnalysisDesc: '我们的AI检测系统会分析您提供的文本，寻找AI生成内容的特征。',
      featureRecognition: '特征识别',
      featureRecognitionDesc: '系统识别词汇多样性、句式结构、语言模式等特征，这些特征可以区分AI和人类撰写的内容。',
      scoreCalculation: '评分计算',
      scoreCalculationDesc: '根据检测到的特征，系统会给出一个0-100%的评分，表示文本被AI生成的可能性。',
      detailedAnalysis: '详细分析',
      detailedAnalysisDesc: '除了评分外，系统还会提供详细的分析报告，指出文本中可能由AI生成的部分。',
      tip: '提示',
      tipText: '如果您的内容被检测为AI生成，可以使用我们的',
      humanizeTool: 'AI内容人性化工具',
      tipEnd: '进行处理，使其更像人类撰写的内容。',
      languageSelection: '选择语言',
      loginNotice: '注意：未登录用户每天只能使用检测功能3次。',
      login: '登录',
      or: '或',
      register: '注册',
      unlockFeatures: '以解锁完整功能。'
    },
    en: {
      title: 'AI Content Detector',
      description: 'Detect if your content is AI-generated and get detailed analysis reports and suggestions.',
      inputLabel: 'Input Text',
      placeholder: 'Paste the text you want to detect (at least 100 characters)...',
      characters: 'characters',
      minChars: '(at least 100 characters recommended)',
      analyzeButton: 'Detect Text',
      analyzing: 'Analyzing...',
      resultTitle: 'Detection Results',
      aiProbability: 'AI Probability',
      humanScore: 'Human Score',
      aiScore: 'AI Score',
      highAi: 'This text is likely AI-generated.',
      mediumAi: 'This text may contain some AI-generated content.',
      lowAi: 'This text is likely written by a human.',
      detailAnalysis: 'Detailed Analysis',
      retestButton: 'Retest',
      humanizeButton: 'Humanize Text',
      enterText: 'Enter text and click "Detect Text" to get analysis results',
      howItWorks: 'How does the AI detector work?',
      contentAnalysis: 'Content Analysis',
      contentAnalysisDesc: 'Our AI detection system analyzes your text, looking for characteristics of AI-generated content.',
      featureRecognition: 'Feature Recognition',
      featureRecognitionDesc: 'The system identifies vocabulary diversity, sentence structure, language patterns, and other features that can distinguish between AI and human-written content.',
      scoreCalculation: 'Score Calculation',
      scoreCalculationDesc: 'Based on detected features, the system gives a 0-100% score indicating the likelihood that the text was generated by AI.',
      detailedAnalysis: 'Detailed Analysis',
      detailedAnalysisDesc: 'In addition to scoring, the system provides a detailed analysis report highlighting parts of the text that may be AI-generated.',
      tip: 'Tip',
      tipText: 'If your content is detected as AI-generated, you can use our',
      humanizeTool: 'AI content humanization tool',
      tipEnd: 'to make it more human-like.',
      languageSelection: 'Select Language',
      loginNotice: 'Note: Unregistered users can only use the detection feature 3 times per day.',
      login: 'Login',
      or: 'or',
      register: 'Register',
      unlockFeatures: 'to unlock full features.'
    }
  };

  // 获取当前选中语言的文本
  const text = selectedLanguage === 'zh' ? langTexts.zh : langTexts.en;

  return (
    <Layout
      title={`${text.title} | Undetectable.AI`}
      description={text.description}
    >
      <div className="py-8 bg-gray-50 min-h-screen">
        <div className="container mx-auto px-4">
          <div className="text-center mb-8">
            <h1 className="text-3xl md:text-4xl font-bold mb-4">{text.title}</h1>
            <p className="text-lg text-gray-600 max-w-2xl mx-auto">
              {text.description}
            </p>
          </div>
          
          {/* 语言选择 */}
          <div className="max-w-md mx-auto mb-6">
            <label className="block text-gray-700 font-medium mb-2">
              {text.languageSelection}
            </label>
            <div className="flex flex-wrap gap-2">
              {languages.map((lang) => (
                <button
                  key={lang.value}
                  className={`px-4 py-2 rounded-md ${
                    selectedLanguage === lang.value
                      ? 'bg-blue-600 text-white'
                      : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
                  }`}
                  onClick={() => setSelectedLanguage(lang.value)}
                >
                  {lang.label}
                </button>
              ))}
            </div>
          </div>
          
          <div className="grid md:grid-cols-2 gap-6">
            {/* 输入区域 */}
            <div className="bg-white p-6 rounded-lg shadow-md">
              <h2 className="text-xl font-semibold mb-4">{text.inputLabel}</h2>
              <textarea
                value={inputText}
                onChange={(e) => setInputText(e.target.value)}
                placeholder={text.placeholder}
                className="w-full h-64 p-4 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              ></textarea>
              <div className="flex justify-between items-center mt-4">
                <div className="text-sm text-gray-500">
                  {inputText.length} {text.characters} 
                  {inputText.length < 100 && inputText.length > 0 && (
                    <span className="text-red-500"> {text.minChars}</span>
                  )}
                </div>
                <button
                  onClick={handleDetection}
                  disabled={isAnalyzing || inputText.length < 10}
                  className={`px-6 py-2 rounded-md ${
                    isAnalyzing || inputText.length < 10
                      ? 'bg-gray-400 cursor-not-allowed'
                      : 'bg-blue-600 hover:bg-blue-700 text-white'
                  }`}
                >
                  {isAnalyzing ? text.analyzing : text.analyzeButton}
                </button>
              </div>
            </div>
            
            {/* 结果区域 */}
            <div className="bg-white p-6 rounded-lg shadow-md">
              <h2 className="text-xl font-semibold mb-4">{text.resultTitle}</h2>
              
              {error && (
                <div className="p-4 bg-red-50 border border-red-200 text-red-700 rounded-md mb-4">
                  {error}
                </div>
              )}
              
              {isAnalyzing ? (
                <div className="flex flex-col items-center justify-center h-64">
                  <div className="w-12 h-12 border-4 border-blue-500 border-t-transparent rounded-full animate-spin mb-4"></div>
                  <p className="text-gray-600">{text.analyzing}</p>
                </div>
              ) : result ? (
                <div>
                  {/* 得分环形图 */}
                  <div className="flex justify-center mb-6">
                    <div className="relative w-48 h-48">
                      <svg className="w-full h-full" viewBox="0 0 100 100">
                        {/* 背景圆环 */}
                        <circle
                          cx="50"
                          cy="50"
                          r="45"
                          fill="none"
                          stroke="#f0f0f0"
                          strokeWidth="10"
                        />
                        {/* AI比例圆环 */}
                        <circle
                          cx="50"
                          cy="50"
                          r="45"
                          fill="none"
                          stroke="#3b82f6"
                          strokeWidth="10"
                          strokeDasharray={`${(result.aiPercent / 100) * 283} 283`}
                          strokeDashoffset="0"
                          transform="rotate(-90 50 50)"
                        />
                      </svg>
                      <div className="absolute inset-0 flex flex-col items-center justify-center">
                        <div className="text-3xl font-bold">{result.aiPercent}%</div>
                        <div className="text-sm text-gray-500">{text.aiProbability}</div>
                      </div>
                    </div>
                  </div>
                  
                  {/* 结果详情 */}
                  <div className="grid grid-cols-2 gap-4 mb-6">
                    <div className="bg-gray-50 p-4 rounded-md text-center">
                      <div className="text-sm text-gray-500">{text.humanScore}</div>
                      <div className="text-2xl font-semibold">{result.humanPercent}%</div>
                    </div>
                    <div className="bg-gray-50 p-4 rounded-md text-center">
                      <div className="text-sm text-gray-500">{text.aiScore}</div>
                      <div className="text-2xl font-semibold">{result.aiPercent}%</div>
                    </div>
                  </div>
                  
                  {/* 结果判断 */}
                  <div className={`p-4 rounded-md mb-6 ${
                    result.aiPercent >= 70 
                      ? 'bg-red-50 border border-red-200 text-red-700' 
                      : result.aiPercent >= 40
                        ? 'bg-yellow-50 border border-yellow-200 text-yellow-700'
                        : 'bg-green-50 border border-green-200 text-green-700'
                  }`}>
                    {result.aiPercent >= 70 
                      ? text.highAi 
                      : result.aiPercent >= 40
                        ? text.mediumAi
                        : text.lowAi
                    }
                  </div>
                  
                  {/* 分析详情 */}
                  <div>
                    <h3 className="font-semibold mb-2">{text.detailAnalysis}</h3>
                    <p className="text-gray-700 whitespace-pre-line">
                      {result.analysis}
                    </p>
                  </div>
                  
                  {/* 操作按钮 */}
                  <div className="mt-6 flex justify-between">
                    <button
                      onClick={() => setResult(null)}
                      className="px-4 py-2 border border-gray-300 rounded-md hover:bg-gray-50"
                    >
                      {text.retestButton}
                    </button>
                    <a
                      href="/humanizer"
                      className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700"
                    >
                      {text.humanizeButton}
                    </a>
                  </div>
                </div>
              ) : (
                <div className="flex flex-col items-center justify-center h-64 text-gray-500">
                  <svg className="w-16 h-16 mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                  </svg>
                  <p className="text-center">
                    {text.enterText}
                  </p>
                </div>
              )}
            </div>
          </div>
          
          {/* 使用说明 */}
          <div className="mt-12 max-w-3xl mx-auto">
            <h2 className="text-xl font-semibold mb-4">{text.howItWorks}</h2>
            <div className="bg-white p-6 rounded-lg shadow-md">
              <ol className="list-decimal pl-5 space-y-3">
                <li className="text-gray-700">
                  <span className="font-medium">{text.contentAnalysis}</span>：{text.contentAnalysisDesc}
                </li>
                <li className="text-gray-700">
                  <span className="font-medium">{text.featureRecognition}</span>：{text.featureRecognitionDesc}
                </li>
                <li className="text-gray-700">
                  <span className="font-medium">{text.scoreCalculation}</span>：{text.scoreCalculationDesc}
                </li>
                <li className="text-gray-700">
                  <span className="font-medium">{text.detailedAnalysis}</span>：{text.detailedAnalysisDesc}
                </li>
              </ol>
              
              <div className="mt-6 p-4 bg-blue-50 border border-blue-200 text-blue-700 rounded-md">
                <h3 className="font-semibold mb-2">{text.tip}</h3>
                <p>{text.tipText} <a href="/humanizer" className="underline">{text.humanizeTool}</a> {text.tipEnd}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
} 